[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
# Add this block to your existing netlify.toml.
# Do not erase your other Netlify settings.

[functions."auto-plan-scheduler"]
  schedule = "@hourly"
